### PR TITLE
Milestone #1

### PR DESCRIPTION
**Pull request by Bismarck-GM**
## Milestone 1:

- Used background property with images and positioned it within the Y and X-axis.
- Created a NavBar with gradients, input and hover properties.
- Styled header picture and fonts to be closest to the clone target.
- Used semantic HTML for structure.
- Corrected CSS errors with Stilelint.

### CODE REVIEW

**Review by sumancrest0001 — CHANGES_REQUESTED** [review]
Fantastic work @Bismarck-GM  :clap: :clap: :+1: 
You created almost the perfect clone of the original site. Everything looks good to me but there is one issue with the width of the site. I checked your project on [githack](https://raw.githack.com/) as well as on crome but there was overflow in the x-axis. Please check on your device as well on  [githack](https://raw.githack.com/). If it looks good then submit for another review with a screenshot. **You can also reach out to me on Slack (Suman Shrestha)**
Currently it looks like this :point_down: 
Screenshot from 2020-05-09 12-41-56

[Optional] Can we change the style the search input field to make similar to that of the original one. It will make your project perfect. 

Happy coding !!

**Comment by Bismarck-GM** [comment]
## Milestone 2:
- Corrected widths so It should not overflow above 1000px.
- Changed some HTML (had too much-nested sections).
- Added border-radius to search input.

**Comment by lekegitrepo** [comment]
#### Hi @Bismarck-GM :100: :1st_place_medal:
#### Good job :+1:  this project is approved.

### Reviewed by Temitayo Adeleke.

- Github: [@lekegitrepo](https://github.com/lekegitrepo)
- Twitter: [@leketemi](https://twitter.com/leketemi)
- Linkedin: [linkedin](https://www.linkedin.com/in/temitayo-adeleke/)

**Review by lekegitrepo — APPROVED** [review]
#### Status: Approved.

**Pull request merged**
